---
driver:
  name: vagrant

platforms:
  - name: centos-6.8
  - name: centos-7.2
  - name: ubuntu-14.04
  - name: ubuntu-16.04
  - name: debian-8.5

provisioner:
  name: salt_solo
  salt_install: bootstrap
  salt_bootstrap_url: https://bootstrap.saltstack.com
  salt_version: latest
  formula: snmp
  pillars:
    top.sls:
      base:
        '*':
          - snmp
    snmp.sls:
      snmp:
        conf:
          sysLocation: 'Right Here'
          sysContact: 'System Admin'
          logconnects: false
          views:
            - name: all
              type: included
              oid: '.1'
              mask: 80
          rocommunities:
            public:
              source:
                - localhost
                - 192.168.0.0/24
                - 192.168.1.0/24
          rwcommunities:
            private:
              source:
                - 192.168.1.0/24
          rousers:
            - username: 'myv3user'
              authpassphrase: 'myv3password'
              view: all
              authproto: 'SHA'
              privproto: 'AES'
              privpassphrase: 'v3privpass'

suites:
  - name: default
    provisioner:
      salt_bootstrap_options: -X -d
      state_top:
        base:
          '*':
            - snmp.conf
